DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
    ID VARCHAR2(50),
    PWD NVARCHAR2(50),
    NAME NVARCHAR2(50),
    GENDER NCHAR(2),
    AGE NUMBER(3),
    BIRTHDAY CHAR(10),
    PHONE CHAR(13),
    REGDATE DATE
);    


CREATE TABLE NOTICE
(
    ID          NUMBER,
    TITLE       NVARCHAR2(100),
    WRITER_ID   NVARCHAR2(50),
    CONTENT     CLOB,
    REGDATE     TIMESTAMP,
    HIT         NUMBER,
    FILES       NVARCHAR2(1000)
);


CREATE TABLE "COMMENT"
(
    ID          NUMBER,
    CONTENT     NVARCHAR2(2000),
    REGDATE     TIMESTAMP,
    WRITER_ID   NVARCHAR2(50),
    NOTICE_ID   NUMBER
);

CREATE TABLE ROLE
(
    ID          VARCHAR(50),
    DESCRIPTION VARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE
(
    MEMBER_ID   NVARCHAR2(50),
    ROLE_ID     VARCHAR(50)
);
INSERT INTO MEMBER(GENDER) VALUES('남성');
INSERT INTO MEMBER(ID, PWD) VALUES('test','111');
UPDATE MEMBER SET PWD='pwd3939' WHERE ID='kim123';
UPDATE MEMBER SET NAME='홍길동' WHERE ID='gugu99';
DELETE MEMBER WHERE NAME IS NULL;
SELECT ID "USER ID" , NAME 이름, PWD 비밀번호 FROM MEMBER;
SELECT  NAME||'('||ID||')' 이름 FROM MEMBER;
SELECT LENGTHB(GENDER) FROM MEMBER;
ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);
ALTER TABLE MEMBER DROP COLUMN AGE;
ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);
INSERT INTO NOTICE(HIT) VALUES(5);
SELECT HIT+1 HIT FROM NOTICE;
SELECT 1||'3' FROM DUAL;





